### ISSUE TITLE
各項目の非表示オプション

### ISSUE THREAD

**Issue by gaojie429** [hirosan18/homebridge-nature-remo-sensor#4]
温度センサー、湿度センサー、照度センサーのそれぞれを個別に表示、非表示にするオプションをConfig.JsonのTrue or Falseで設定できるようにしていただきたいのですが、可能でしょうか？

**Comment by hirosan18** [comment]
対応検討しますので少々お待ち下さい。

**Comment by gaojie429** [comment]
わかりました、ありがとうございます！

**Comment by hirosan18** [comment]
npmにv1.2.0として公開しました。
https://www.npmjs.com/package/homebridge-nature-remo-sensor

`config.json`に以下のように`sensors`を追加して、`temperature` `humidity` `light` で非表示にしたいセンサーのみ`false`を指定すればそのセンサーはHomeアプリ上には出てこなくなると思います。
(例では`true`も指定してますが、`true`のセンサーは書かなくても問題ないです)
```
  "accessories": [{
    "accessory": "remo-sensor",
    "name": "センサー",
    "deviceName": "<DeivceNickName>",
    "mini": false,
    "schedule": "*/5 * * * *",
    "accessToken": "<https://home.nature.global/で取得したAccess token>",
    "sensors": {
      "temperature": true,
      "humidity": true,
      "light": false
    }
  }]
```
なにか問題あれば教えてください！

**Comment by gaojie429** [comment]
早速の対応、ありがとうございます！
当環境にも最新版をインストールし、例示してくださった通りにConfigを書いたところ"false"で指定したセンサーを問題なく非表示することができました！

私は、Nature Remoプラグインとしてこのプラグインの他にも、エアコン操作用のプラグインを導入しており、現在の室内の温度表示がこのプラグインと競合していたため、すごく助かりました！

**Comment by hirosan18** [comment]
いえ、他にも問題/リクエスト等あればissueください👍
このissueは問題ないようなのでcloseします
