### ISSUE TITLE
センサーが「応答なし」になってしまう

### ISSUE THREAD

**Issue by gaojie429** [hirosan18/homebridge-nature-remo-sensor#5]
Homebridgeを起動してしばらくすると、全てのセンサーがHomeアプリ上で「応答なし」と表示され、Siriでもその状態を確認できなくなってしまいます。Homebridgeを再起動すれば、再び正常に動くのですが、何かの拍子に(時間経過なのか、何か別のアクセサリを操作したからなのかはわかりませんが)「応答なし」となってしまいます。

こちらが、その時のログです。
正常に作動時
```
[2019-2-7 21:46:07] [Remoセンサー] > [Getting] humidity
[2019-2-7 21:46:07] [Remoセンサー] >> [request]
[2019-2-7 21:46:07] [Remoセンサー] > [Getting] temperature
[2019-2-7 21:46:07] [Remoセンサー] > [Getting] humidity
[2019-2-7 21:46:07] [Remoセンサー] > [Getting] temperature
[2019-2-7 21:46:07] [Remoセンサー] > [Getting] light
[2019-2-7 21:46:07] [Remoセンサー] >>> [Getting] humidity => 40
[2019-2-7 21:46:07] [Remoセンサー] >>> [Getting] temperature => 26
[2019-2-7 21:46:07] [Remoセンサー] >>> [Getting] humidity => 40
[2019-2-7 21:46:07] [Remoセンサー] >>> [Getting] temperature => 26
[2019-2-7 21:46:07] [Remoセンサー] >>> [Getting] light => 208.8
[2019-2-7 21:46:07] [Remoセンサー] > [Getting] light
[2019-2-7 21:46:07] [Remoセンサー] >> [request]
[2019-2-7 21:46:08] [Remoセンサー] >>> [Getting] light => 208.8
```

「応答なし」となる時
```
[2019-2-7 21:45:27] [Remoセンサー] > [Getting] humidity
[2019-2-7 21:45:27] [Remoセンサー] > [Getting] temperature
[2019-2-7 21:45:27] [Remoセンサー] > [Getting] light
[2019-2-7 21:45:34] [Remoセンサー] > [Getting] humidity
[2019-2-7 21:45:34] [Remoセンサー] > [Getting] temperature
[2019-2-7 21:45:34] [Remoセンサー] > [Getting] light
```

値が返ってきてないようなのでAPIアクセスに何か問題があるのでしょうか？

**Comment by hirosan18** [comment]
@gaojie429 
NatureRemoのCloudAPIには回数制限があります。
https://developer.nature.global/

scheduleの値はどんな設定にしてますか？

**Comment by gaojie429** [comment]
@hirosan18 
5分間に30回なんですね・・・
スケジュールはこのように設定しています。
`"schedule": "*/5 * * * *"`
デフォルトのままです。
また、Nature Remoでエアコンを操作するプラグインでは、当プラグインが「応答なし」状態にあっても温度取得、エアコンの操作ともに問題なくできているので回数制限に引っかかったというわけではなさそうです。

**Comment by hirosan18** [comment]
@gaojie429 
発生契機が不明、かつ再現できていないので、時間がかかると思いますが、デバッグしてみます。
一応、他のCloudAPIを使用するプラグインを頻繁に操作すると上限に達すると思うので、それ契機で起こるか試してみてください。

**Comment by hirosan18** [comment]
デバッグしてみた限り、やはりAPI上限に達していると思われます。
本プラグインは内部で計測値を保持していないため、APIエラーになった場合、Homebridge側にエラーを通知しますが、その際のエラー表示(応答なし)は一旦ホームに戻ってからHomeアプリを再表示するなどしないと表示が更新されません。(homebridge-nature-remo-airconを使用していると思いますが、homebridge-nature-remo-airconは内部に計測値を保持した状態で動作するため、APIエラーになったとしてもエラー表示になりません。しかし、温度変更等はエラーになると思います)
v1.2.1で、エラーになった場合にログを出力するように微修正しましたので、そちらで、同様の状態になった場合に ` >>> [Error] "Error: 429"` と出力されるようでしたら、API上限が原因です。
試してみてください。

**Comment by gaojie429** [comment]
@hirosan18 デバッグありがとうございます。
こちらの環境では一旦「応答なし」と表示された後はHomeアプリを再起動したり、再読み込みしても「応答なし」のままとなっており、この状況でもNature-Remo-Airconでの温度変更は可能となっています。
(Homebridge自体を再起動すると、再び問題なく動作しますが、何かの弾みで再び「応答なし」となります...)
1.2.1を導入し、しばらく様子を見て、また同様の問題が発生しましたらお伝えします。

**Comment by gaojie429** [comment]
v1.2.1を導入後、1〜2時間後に様子を確認したところ、再び「応答なし」となったのでログを確認したところ、以下のようになっていました。
```
[2019-2-8 07:02:41] [Remoセンサー] > [Getting] humidity
[2019-2-8 07:02:41] [Remoセンサー] > [Getting] temperature
[2019-2-8 07:02:41] [Remoセンサー] > [Getting] light
[2019-2-8 07:02:41] [Remoセンサー] >>> [Error] "Error: getaddrinfo ENOTFOUND api.nature.global api.nature.global:443"
[2019-2-8 07:02:41] [Remoセンサー] >>> [Error] "Error: getaddrinfo ENOTFOUND api.nature.global api.nature.global:443"
[2019-2-8 07:02:41] [Remoセンサー] >>> [Error] "Error: getaddrinfo ENOTFOUND api.nature.global api.nature.global:443"
```
API制限とはまた別の問題のようです・・・

**Comment by hirosan18** [comment]
@gaojie429 
どうやら、nodeモジュールがdnsの正引きに失敗しているようです。
回避可能か調査してみます。

**Comment by hirosan18** [comment]
@gaojie429
念の為、動作環境教えてもらってもいいでしょうか？
(OSやnodeのバージョン、IPv6の有無など)

**Comment by gaojie429** [comment]
@hirosan18 
お手数をおかけしてすみません。
動作環境は以下の通りです
PC: Mac mini (Late 2012)
OS: Mac OS X Mojave (10.14.2)
IPv6:あり (ただし、IPv4,IPv6両方で当現象は発生しました)
Nodeバージョン: v10.15.0
Homebridgeバージョン: 0.4.46
導入NodeModule:
- npm
- homebridge-nature-remo-aircon
- homebridge-people-plus
- homebridge-hue
- homebridge-securitysystem
- homebridge-tuya
- homebridge-automation-calendar
- homebridge-nature-remo-sensor
- homebridge-config-ui-x

です。新たに必要な情報等ありましたら、おしらせください。

**Comment by hirosan18** [comment]
@gaojie429 
情報提供ありがとうございます！
正常な状態とエラーの状態の双方で、
`nslookup api.nature.global`
がどのような出力になるか、該当のMacminiで試してみてもらってもいいでしょうか？
(他のプラグインが同様の状態にならないことをみると、本プラグインが使用しているnodeのhttpsモジュールに関連するなんらかのライブラリのバグの可能性もあるので、nslookupの結果は正常値の可能性が高いですが、一応確認しておきたいです)

**Comment by gaojie429** [comment]
正常時の実行結果です。
```
Non-authoritative answer:
api.nature.global	canonical name = api2-584300998.us-east-1.elb.amazonaws.com.
Name:	api2-584300998.us-east-1.elb.amazonaws.com
Address: 52.73.52.108
Name:	api2-584300998.us-east-1.elb.amazonaws.com
Address: 52.23.3.239
Name:	api2-584300998.us-east-1.elb.amazonaws.com
Address: 52.44.170.71
Name:	api2-584300998.us-east-1.elb.amazonaws.com
Address: 54.227.73.195
```

エラー状態に関しましては、
先ほどHomebridgeサーバーを再起動し正常状態に戻したため、再び問題が発生するまでお待ちください。

**Comment by hirosan18** [comment]
@gaojie429
同様の環境を構築し、３,４時間試して見た限りでは本問題は発生しませんでした。
```
MacBook Pro 2017
Mojave 10.14.2
IPv6あり
node ver 10.15.0
homebridge ver 0.4.46
```
```
Raspberry Pi 3 Model B+
Raspbian 9.4
IPv6あり
node ver 10.15.0
homebridge ver 0.4.46
```
環境固有の問題の可能性が高いので、再現した場合に取得可能な情報の取得と、各モジュールのアップデートやdns周りのキャッシュ更新など考えうる対応で改善しないか確認してください。
それでも治らない場合、本プラグインが使用しているnode標準モジュール `https` を他のモジュールに置き換えることを検討しようと思います。

**Comment by gaojie429** [comment]
@hirosan18 わざわざ同様環境の構築、検証までしていただきありがとうございます。
当方もしばらく「応答なし」現象が発生しなかったのでそのまま放置していたのですが、先ほど確認したところ再び発生したのでnsloolupコマンドを実行してみました。
```
Non-authoritative answer:
api.nature.global	canonical name = api2-584300998.us-east-1.elb.amazonaws.com.
Name:	api2-584300998.us-east-1.elb.amazonaws.com
Address: 34.205.167.24
Name:	api2-584300998.us-east-1.elb.amazonaws.com
Address: 52.44.170.71
Name:	api2-584300998.us-east-1.elb.amazonaws.com
Address: 52.23.3.239
Name:	api2-584300998.us-east-1.elb.amazonaws.com
Address: 54.227.73.195
```
これも、特に正常時と変わった点はないので、固有の現象かもしれませんね。。
とりあえず指示の通りに考えられる対処を行ってみます。

**Comment by hirosan18** [comment]
@gaojie429 
いろいろ対処しても改善しなかった場合、
お手数ですが、`change_http_module` ブランチのコードをチェックアウトして
動作検証していただいてもよろしいでしょうか？

httpsモジュールではなく、`homebridge-nature-remo-aircon`と同じく[request](https://github.com/request/request)モジュールを使用するようにしたので、`homebridge-nature-remo-aircon`で現象発生しないのでしたら、 `change_http_module` ブランチのコードを使用することで現象が発生しなくなると思います。

**Comment by gaojie429** [comment]
@hirosan18 考えられる対処法を試しましたが、結局有効なものはなかったので
`change_http_module`をチェックアウトしたバージョンのプラグインで昨日の夜八時ごろから運用していますが、24時間以上経過した現在も正常に動いています！今まで24時間以上正常に動いていたことはなかったので、大丈夫そうです！
本当にありがとうございました！！
後二日間問題なく動作することを確認したら、このIssueを閉じさせていただこうと思います。

**Comment by hirosan18** [comment]
@gaojie429
検証ありがとうございます。
マージしたものを1.3.0としてnpmにpublishしているので、
そちらで運用してみてください。

**Comment by gaojie429** [comment]
@hirosan18
1.3.0をしばらく運用したところ、全く「応答なし」となることなく動作してくれました！
長期間にわたり修正を行っていただき、ありがとうございました！

これにてIssueを閉じさせていただきます…
