### ISSUE TITLE
温度の表示オプション

### ISSUE THREAD

**Issue by gaojie429** [hirosan18/homebridge-nature-remo-sensor#7]
度々リクエストすみません。
温度センサが表示する値に関してです。
こちらの画像のように現在の温度がより大きく表示された方が見やすいなと思ったのですが、
小数第1位を四捨五入した値を表示するオプションを用意していただくことは可能でしょうか？

![img_0539](https://user-images.githubusercontent.com/36978407/52904015-13674280-3269-11e9-80ba-30d937f8487a.jpeg)

**Comment by hirosan18** [comment]
@gaojie429 
小数点以下が表示されるのはHomeBridgeの仕様です。
https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L677
また、HomeKitTypesの該当部分を変更して動作確認しましたが、
望む表示にはならなかったので厳しそうです。

**Comment by gaojie429** [comment]
HomeBridgeの仕様だったんですか…
一応homebridgeの方にもリクエストを送信してみます。
試行、動作確認の方ありがとうございました！
一応、homebridge製作者側からなんらかの返答があるまでこのIssueはそのままにしておきます。

**Comment by hirosan18** [comment]
@gaojie429 
少し語弊があったので、訂正します。
> 小数点以下が表示されるのはHomeBridgeの仕様です。

ただしくは、
`HomeBridgeが使用しているHAP-NodeJSの実装に従っています。` です。
HAP-NodeJSの実装の根拠が、Homekitの仕様なのか、iOSの仕様なのかは調べてみないとわかりませんが、
私が試した限り、HAP-NodeJSのコードを改変して、温度をINTで通知しても、私のiPhone上のHomeアプリでは小数点以下非表示にすることはできませんでした。
ですので、HomeBridgeの方にリクエストしても解決しない可能性が高いです。
私の検証が間違っている可能性もあるので、一度ご自身で関連するモジュールの該当部分を改変を試してみて、対応可能だった場合にプルリクを出す形のほうがいいかもしれません。

**Comment by gaojie429** [comment]
@hirosan18
こちらでもsetPropsで
minStepを1.0にしたり、formatをINTにしたりしてみましたがxx.0と表示されて0は消えませんでした。
どうやらiOS12以降のHomekitの仕様の様です。
もし解決策が見つかればPRしようと思います。

**Comment by hirosan18** [comment]
@gaojie429 
了解です。
このIssueはクローズしてしまいますね。
また何かリクエスト等あればIssueください！
