### ISSUE TITLE
複数のNature Remoのセンサー情報

### ISSUE THREAD

**Issue by takamasa-arch** [hirosan18/homebridge-nature-remo-sensor#8]
自宅にNature RemoとNature Remo miniがあるのですが、同じようにアクセサリーとして追加してしまうと、以下のように出てしまい追加することが出来ませんでした。

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory:

本プラグインは複数台のNature Remoデータを取得することは出来ないのでしょうか？

**Comment by hirosan18** [comment]
1. ~/.homebridge/accessoriesを削除して再実行してもだめでしたか？
2. ~/.homebridge/config.jsonにはどのように記載していますか？

**Comment by takamasa-arch** [comment]
即レスありがとうございます。ご指摘の通りでした。
~/.homebridge/accessoriesを削除して再度実行したら、上手く行きました。

**Comment by hirosan18** [comment]
うまくいってよかったです🙌
他に問題ないと思うので、このIssueはCloseします！
